### ISSUE TITLE
Crashing at ToA Wardens when taking a screenshot

### ISSUE THREAD

**Issue by jamolnng** [117HD/RLHD#239]
**Describe the bug**
Recently (within the last month) RuneLite has been freezing when taking screenshots within ToA. The crashing has mostly happened when taking screenshots at the end of p4 or when screenshot of opening the chest at the end, but it also did crash once in the transition between p3 and p4 wardens.  There is an existing issue within the RuneLite repo that may be related, https://github.com/runelite/runelite/issues/16597 , however the log I have suggests it may be related 117HD

**To Reproduce**
Take a screenshot at the end of p4 wardens or of the chest loot in the final room

**Expected behavior**
Screenshots can successfully be taken without crashing

**Error**
```
2023-09-24 22:13:23 EDT [Client] ERROR client-patch - Client error
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at rs117.hd.HdPlugin.screenshot(HdPlugin.java:2205)
	at rs117.hd.HdPlugin$$Lambda$2207/0x0000000100c9ec40.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2113)
	at bb.ab(bb.java:54018)
	at bb.run(bb.java:339)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - RuneLite version: 2.6.8

**Comment by aHooder** [comment]
This is indeed the same issue, which is mostly unrelated to 117 HD. The plugin only requires a few megabytes of Java heap space as far as I know, so you are likely reaching the limit either due to having too many hub plugins installed for RuneLite's default memory limit, or one or more of your hub plugins are misbehaving and leaking memory. The vast amount of memory which 117 HD uses is in the form of off-heap buffers, so it doesn't have an impact on this Java heap space limit. The solution in your case is to either up the memory limit and see if that resolves it, or uninstall some hub plugins, or possibly identify which plugin(s) may be leaking memory.

**Comment by jamolnng** [comment]
Thank you, this is what I assumed. A heap dump showed only 12MB of heap space used during regular gameplay. I will try to get one during p4 wardens in ToA to see if anything changes
