### ISSUE TITLE
Teleporting near Hosidius grape vines causes client crash

### ISSUE THREAD

**Issue by tylerwgrass** [117HD/RLHD#429]
**Describe the bug**
After using a teletab to Falador from the Hosidius grape vine bank chest, the client crashed.

**To Reproduce**
Haven't reproduced

**Expected behavior**
No crash

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.10.31.3
 - Launcher version: 2.7.1

**Additional context**
Logs:
> 2024-06-06 00:16:01 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1270, y=3728, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:41:05 PDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 4, previous observed offset was 31 (1) Player Loc:WorldPoint(x=1809, y=3566, plane=0)
2024-06-06 00:50:47 PDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.IndexOutOfBoundsException: Varbit 10733 does not exist
	at client.getVarbitValue(client.java:54049)
	at client.getVarbitValue(client.java:11957)
	at rs117.hd.scene.LightManager.trackImpostorChanges(LightManager.java:783)
	at rs117.hd.scene.LightManager.handleObjectSpawn(LightManager.java:755)
	at rs117.hd.scene.LightManager.handleObjectSpawn(LightManager.java:727)
	at rs117.hd.scene.LightManager.onGameObjectSpawned(LightManager.java:1010)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:202)
	at jy.gb(jy.java:40796)
	at jy.xp(jy.java:16465)
	at client.fd(client.java:55043)
	at client.kr(client.java:57730)
	at client.ii(client.java:3098)
	at client.bp(client.java:1156)
	at be.ag(be.java:371)
	at be.fk(be.java)
	at be.run(be.java:31308)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-06-06 00:50:47 PDT [Client] ERROR client-patch - Client error
java.lang.IndexOutOfBoundsException: Varbit 10733 does not exist
	at client.getVarbitValue(client.java:54049)
	at client.getVarbitValue(client.java:11957)
	at rs117.hd.scene.LightManager.trackImpostorChanges(LightManager.java:783)
	at rs117.hd.scene.LightManager.handleObjectSpawn(LightManager.java:755)
	at rs117.hd.scene.LightManager.loadSceneLights(LightManager.java:650)
	at rs117.hd.HdPlugin.swapScene(HdPlugin.java:2380)
	at client.fd(client.java:19105)
	at client.kr(client.java:57730)
	at client.ii(client.java:3098)
	at client.bp(client.java:1156)
	at be.ag(be.java:371)
	at be.fk(be.java)
	at be.run(be.java:31308)
	at java.base/java.lang.Thread.run(Unknown Source)

`Varbit 10733` seems to correspond to the NPC [Meredith](https://oldschool.runescape.wiki/w/Meredith) at the GE.
 https://static.runelite.net/api/runelite-api/constant-values.html#net.runelite.api.Varbits

**Comment by aHooder** [comment]
Thanks for the detailed error report. This will be fixed in the next release.
